title: TC S2025 projekti. Rooleina = UI/UX, Liiketoiminta
description: Projektin tavoitteena oli suunnitella ja toteuttaa selainpohjainen palvelu (Synerra), joka helpottaa kilpailullisten videopelien pelaajia löytämään sopivaa peliseuraa. Palvelun ydinidea on tarjota käyttäjille mahdollisuus etsiä pelikavereita erilaisten filttereiden perusteella sekä mahdollistaa ”syvempi” tutustuminen reaaliaikaisen chatin avulla.
theme: jekyll-theme-minimal
